apiVersion: v1
kind: Service
metadata:
  labels:
    app: dandc-classifier
  name: dandc-classifier
spec:
  ports:
  - name: predict
    port: 5060
    targetPort: 5060
  selector:
    app: dandc-classifier
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dandc-classifier
  name: dandc-classifier
spec:
  selector:
    matchLabels:
      app: dandc-classifier
  template:
    metadata:
      labels:
        app: dandc-classifier
    spec:
      containers:
      - image: kaejong/bentoml-dandc-serving:v0.2
        name: dandc-classifier
        ports:
        - containerPort: 5060
