version: '3'
services:
  minio:
    image: minio/minio
    command: server /data --address "0.0.0.0:9090" --console-address "0.0.0.0:9001"
    container_name: minio 
    environment:
      MINIO_ROOT_USER: minio 
      MINIO_ROOT_PASSWORD: minio123 
    restart: always
    shm_size: '1gb' 
    ports:
      - "9090:9090" 
      - "9001:9001"
    volumes:
      - /mnt/data:/data  
